services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: change_me
    volumes:
      - db_data_pennywise:/var/lib/postgresql/pennywise/data

volumes:
  db_data_pennywise:
